version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r requirements.txt

  pre_build:
    commands:
      - mkdir -p reports
      - pytest --junitxml=reports/test-results.xml

  build:
    commands:
      - zip artifact.zip handler.py

reports:
  arn:aws:codebuild:us-east-1:727646513964:report-group/pytest-report:
    files:
      - reports/*.xml
    base-directory: reports
    file-format: JUNITXML

artifacts:
  files:
    - artifact.zip